### ISSUE TITLE
Is it possible for someone to move the ownership of this repo into their personal profile?

### ISSUE THREAD

**Issue by pet3r-pan** [ethereum-magicians/berlin-council#6]
Is it possible for someone to move the ownership of this repo into their personal profile?

It kinda bugs me that in the ethereum-magicians org that this is the only repo that is an event lol

**Comment by bmann** [comment]
it's basically archived info! Can you please move this to an issue in scrolls? Jamie has this power maybe (and could move it under my @bmann account).

I know Jamie is pretty swamped at the moment, so this is also likely to be low priority.

**Comment by pet3r-pan** [comment]
Moved https://github.com/ethereum-magicians/scrolls/issues/23
